name: Testes Automatizados

on:
  push:
    branches:
      - main  # Executa o workflow em qualquer commit na branch 'main'

jobs:
  test:  # Nome do job
    runs-on: ubuntu-latest  # Ambiente onde o workflow será executado

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3  # Baixa o código do repositório

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Versão do Python a ser usada

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip  # Atualiza o pip
        pip install pytest  # Instala o pytest para rodar os testes

    - name: Rodar os Testes
      run: |
        pytest  # Executa os testes presentes no repositório
